### ISSUE TITLE
compiling always throwing an error

### ISSUE THREAD

**Issue by jukindle** [duckietown/docs-software_devel#5]
`make compile-docker` throws 

`docker: Error response from daemon: invalid volume specification: '--show-superproject-working-tree:--show-superproject-working-tree': invalid mount config for type "volume": invalid mount path: '--show-superproject-working-tree' mount path must be absolute.`

Reason for this seems to be that `git rev-parse --show-superproject-working-tree` outputs `--show-superproject-working-tree` for some strange reason.

If `-v $(gitdir_super):$(gitdir_super) \` is commented out from the `make compile-docker` command, it seems to be working with this repo. With "docs-opmanual_duckietown", this "fix" does not work.

**Comment by liampaull** [comment]
is this still an issue?
